### ISSUE TITLE
Cannot update to the latest version on Arch Linux

### ISSUE THREAD

**Issue by set-killer** [atom-community/zadeh#79]
Hello,
My current version of Atom is 1.56.0 x64

I have installed an older version of atom-ide-vue - 1.3.1 which is working fine. But now i want to update to the latest version (1.4.6).
But when i try to update to the latest version there is an error:

```
> zadeh@3.0.0-beta.2 install /tmp/apm-install-dir-2021410-6757-zo74x0.n9he/node_modules/atom-ide-vue/node_modules/zadeh
> node-gyp-build


npm WARN deprecated tslint@6.1.3: TSLint has been deprecated in favor of ESLint. Please see https://github.com/palantir/tslint/issues/4534 for more information.
sh: line 1: /tmp/apm-install-dir-2021410-6757-zo74x0.n9he/node_modules/atom-ide-vue/node_modules/.bin/node-gyp-build: Permission denied
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-2021410-6757-zo74x0.n9he/package.json'
npm WARN apm-install-dir-2021410-6757-zo74x0.n9he No description
npm WARN apm-install-dir-2021410-6757-zo74x0.n9he No repository field.
npm WARN apm-install-dir-2021410-6757-zo74x0.n9he No README data
npm WARN apm-install-dir-2021410-6757-zo74x0.n9he No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 126
npm ERR! zadeh@3.0.0-beta.2 install: `node-gyp-build`
npm ERR! Exit status 126
npm ERR! 
npm ERR! Failed at the zadeh@3.0.0-beta.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
I have other addons that just got updated successfully. 
I'm using Archlinux.

**Comment by set-killer** [comment]
Okay,
Archlinux has rolling release system. It does not have versioning like Ubuntu or Fedora. It has the latest and greatest packages in it. I have updated it like 2 days ago.
The processor is pretty much standard Intel mobile CPU with x86_64 architecture.
In the repository there are the following glibc  libraries:

```
core/glibc 2.33-4 [installed]
    GNU C Library
core/lib32-glibc 2.33-4
    GNU C Library (32-bit)
```
where only the first one is installed.

**Comment by aminya** [comment]
I moved the issue to the relevant repository.

The error message says _permission denied_, which is a strange error. I don't think node-gyp-build requires any special permissions for picking up prebuilds. If it cannot find prebuilds, it will try to build from the source.

Please extract the following somewhere on your disk, go to the `zadeh` folder, and run `apm install --production --verbose`. Let me know the resulting log.
[zadeh.zip](https://github.com/atom-community/zadeh/files/6456322/zadeh.zip)

**Comment by set-killer** [comment]
It's successfully installed:
```
[zadeh-3.0.0-beta.2]$ apm install --production --verbose
Installing modules npm WARN deprecated mkdirp@0.3.5: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated babel-eslint@7.2.3: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
npm WARN deprecated rollup-plugin-node-resolve@3.4.0: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-node-resolve.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported

> zadeh@3.0.0-beta.2 install /home/user/Downloads/zadeh-3.0.0-beta.2
> node-gyp-build

npm WARN notsup Unsupported engine for vscode-json-languageservice@4.1.3: wanted: {"npm":">=7.0.0"} (current: {"node":"16.1.0","npm":"6.14.9"})
npm WARN notsup Not compatible with your version of node/npm: vscode-json-languageservice@4.1.3
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.1 (node_modules/rollup/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN eslint-config-airbnb@18.2.1 requires a peer of eslint-plugin-react-hooks@^4 || ^3 || ^2.3.0 || ^1.7.0 but none is installed. You must install peer dependencies yourself.
npm WARN rollup-plugin-assemblyscript@2.0.0 requires a peer of as-bind@* but none is installed. You must install peer dependencies yourself.

audited 780 packages in 5.59s
found 1 high severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
✓
```

**Comment by aminya** [comment]
Maybe the issue is in the installed files. Could you retry installing atom-ide-vue?

```
apm uninstall atom-ide-vue
apm install atom-ide-vue
```

**Comment by set-killer** [comment]
Nope, that didn't worked. I got the same error :(
This is the error message from the file `/home/user/.atom/.apm/_logs/2021-05-11T14_44_12_185Z-debug.log`

```
4273 verbose stack Error: zadeh@3.0.0-beta.2 install: `node-gyp-build`
4273 verbose stack Exit status 126
4273 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/atom-package-manager/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
4273 verbose stack     at EventEmitter.emit (node:events:365:28)
4273 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/atom-package-manager/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
4273 verbose stack     at ChildProcess.emit (node:events:365:28)
4273 verbose stack     at maybeClose (node:internal/child_process:1067:16)
4273 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
4274 verbose pkgid zadeh@3.0.0-beta.2
4275 verbose cwd /tmp/apm-install-dir-2021411-10357-s1ngdd.q9ac
4276 verbose Linux 5.12.1-arch1-1
4277 verbose argv "/usr/bin/node" "/usr/lib/node_modules/atom-package-manager/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/user/.atom/.apm/.apmrc" "--userconfig" "/home/user/.atom/.apmrc" "install" "https://www.atom.io/api/packages/atom-ide-vue/versions/1.4.6/tarball" "--target=9.4.4" "--disturl=https://atom.io/download/electron" "--arch=x64" "--global-style"
4278 verbose node v16.1.0
4279 verbose npm  v6.14.9
4280 error code ELIFECYCLE
4281 error errno 126
4282 error zadeh@3.0.0-beta.2 install: `node-gyp-build`
4282 error Exit status 126
4283 error Failed at the zadeh@3.0.0-beta.2 install script.
4283 error This is probably not a problem with npm. There is likely additional logging output above.
4284 verbose exit [ 126, true ]
```

**Comment by set-killer** [comment]
When i ran `apm install --production --verbose` inside the `zadeh` directory (from the previous step), where did that got installed? Do i need to clean up anything after that?
Thanks!

**Comment by aminya** [comment]
I released a new version. Could you check to see if it made any difference?

**Comment by set-killer** [comment]
Hello @aminya  and thank you for your help.

My current version of Atom is 1.57.0 x64
I still have the same problem. 

When i run apm install atom-ide-vue i get the following output:
```
$> apm install atom-ide-vue
Installing atom-ide-vue to /home/user/.atom/packages ✗

> zadeh@3.0.0-beta.2 install /tmp/apm-install-dir-202159-3182-1wgtak9.xxio/node_modules/atom-ide-vue/node_modules/zadeh
> node-gyp-build


npm WARN deprecated tslint@6.1.3: TSLint has been deprecated in favor of ESLint. Please see https://github.com/palantir/tslint/issues/4534 for more information.
sh: line 1: /tmp/apm-install-dir-202159-3182-1wgtak9.xxio/node_modules/atom-ide-vue/node_modules/.bin/node-gyp-build: Permission denied
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-202159-3182-1wgtak9.xxio/package.json'
npm WARN apm-install-dir-202159-3182-1wgtak9.xxio No description
npm WARN apm-install-dir-202159-3182-1wgtak9.xxio No repository field.
npm WARN apm-install-dir-202159-3182-1wgtak9.xxio No README data
npm WARN apm-install-dir-202159-3182-1wgtak9.xxio No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 126
npm ERR! zadeh@3.0.0-beta.2 install: `node-gyp-build`
npm ERR! Exit status 126
npm ERR! 
npm ERR! Failed at the zadeh@3.0.0-beta.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.atom/.apm/_logs/2021-06-09T08_49_57_789Z-debug.log
```

This directory `/tmp/apm-install-dir-202159-3182-1wgtak9.xxio/` has permissions 700, while everything inside it has permissions 755. I don't know if that is related or not... I guess everything runs with the same user...


The atom-ide-vue package is still linked to zadeh@3.0.0-beta.2  I checked the branches but i couldn't find any branch that has bumped the zadeh dependency to zadeh3-beta3.

**Comment by aminya** [comment]
@set-killer I added the prebuilds that are required by Arch Linux in #83 🎉

**Comment by set-killer** [comment]
Awesome!
Thank you very much.

**Comment by set-killer** [comment]
I think there is some other issue.
I have downloaded the newest master of the zadeh library and extracted it in the download directory. Then inside that directory i ran ```apm install --production --verbose``` and everything went smoothly. 
```
> zadeh@3.0.0-beta.4 install /home/user/Downloads/zadeh-master
> node-gyp-build

(node:16377) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
make: Entering directory '/home/user/Downloads/zadeh-master/build'
  CXX(target) Release/obj.target/zadeh/src/binding/node.o
  SOLINK_MODULE(target) Release/obj.target/zadeh.node
  COPY Release/zadeh.node
make: Leaving directory '/home/user/Downloads/zadeh-master/build'
npm WARN notsup Unsupported engine for vscode-json-languageservice@4.1.4: wanted: {"npm":">=7.0.0"} (current: {"node":"16.3.0","npm":"6.14.9"})
npm WARN notsup Not compatible with your version of node/npm: vscode-json-languageservice@4.1.4
npm WARN eslint-config-airbnb@18.2.1 requires a peer of eslint-plugin-react-hooks@^4 || ^3 || ^2.3.0 || ^1.7.0 but none is installed. You must install peer dependencies yourself.

audited 1069 packages in 10.67s
found 3 high severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
✓
```


Then i extracted the same archive in the ```/tmp``` directory and ran the same command ```apm install --production --verbose``` and then i got the same error: Permission denied.

```
> zadeh@3.0.0-beta.4 install /tmp/test/zadeh-master
> node-gyp-build

sh: line 1: /tmp/test/zadeh-master/node_modules/.bin/node-gyp-build: Permission denied
npm ERR! code ELIFECYCLE
npm ERR! errno 126
npm ERR! zadeh@3.0.0-beta.4 install: `node-gyp-build`
npm ERR! Exit status 126
npm ERR! 
npm ERR! Failed at the zadeh@3.0.0-beta.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.atom/.apm/_logs/2021-06-25T22_28_52_114Z-debug.log
✗
```

By default, when i try to install an Atom package from the GUI, those package and it's dependencies are downloaded in the /tmp directory.

**Comment by set-killer** [comment]
Basically i have mounted my ```/tmp``` partition with an option ```noexec``` which forbids the execution of any files there. So even if the file has +x permissions, they are not being executed. 
The strange thing here is that i have my linux for many years and there was no other situation where I had to execute something from the /tmp directory. No other app from the apps that i use executes scripts from the tmp.

Anyway, everything is fine now and works as it should. Sorry for making you troubles.

**Comment by aminya** [comment]
@set-killer That's great to hear. can you install the latest version of atom-ide-outline now?

**Comment by set-killer** [comment]
@aminya Yes, i have managed to install both `atom-ide-outline` and `atom-ide-vue`. Everything works now.
Thank you very much for the help and for the guidance. I wouldn't resolve this by myself.
